app:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:6543/amingres
      username: amingres
      password: 'pss'
      pool-size: 30

server:
  error:
    include-binding-errors: always
    include-message: always
